aula/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HelloWordController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PostController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', HelloWordController::class);
Route::resource('/user',UserController::class);
Route::resource('/posts',PostController::class);

aula/app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $table='posts';
}

aula/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       /** if($request->has('title')){
            echo 'Tem título: '.$request->title;

        dd($request->only(['title','slug']));

        dd($request->except(['title','slug']));

        dd($request->input('date','28-05-2021'));

        return response('Resposta ok',200);

           return response('{Resposta ok}',200)->header('Content-Type','application/json');

           return response('{Resposta ok}',200)->cookie('autorizado','ok',6);

           return redirect('/');

         return redirect()->route('principal');

       return back();

        */
        $tabela=New Tabela();
        $tabela->title =$request.title;
        $tabela->description=$request.description;
        $tabela->content=$request.content;
        $tabela->slug=$request.slug;
        $tabela->save();
        return back()->withInput();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

aula/resources/views/posts/create.blade.php
<form action="{{route('posts.store')}}" method="post">
    @csrf
    <div class="form-group">
        <label for="title">Título:</label>
        <input type="text" name="title" id="title" class="form-control" value="{{old('title')}}">

    </div>

    <div class="form-group">
        <label for="description">Descrição:</label>
        <input type="text" name="description" id="description" class="form-control" value="{{old('description')}}">
    </div>
    <div class="form-group">
        <label for="content">Conteúdo</label>
        <textarea name="content" cols="30" rows="10" id="content" class="form-control">{{old('content')}}</textarea>

    </div>
    <div class="form-group">
        <label for="slug">Slug:</label>
        <input type="text" name="slug" id="slug" class="form-control" value="{{old('slug')}}">
    </div>

    <button class="btn btn-lg btn-success" type="submit">Criar Postagem</button>

</form>